version: 2.1

# -------------------------------------------------------------------------------------
# Executors
# -------------------------------------------------------------------------------------
executors:
  gpu_cuda10:
    environment:
      CUDA_VERSION: "10.2"
      CUDA_HOME: "/usr/local/cuda"
      PYTHONUNBUFFERED: 1
    machine:
      image: ubuntu-2004:202107-02
    resource_class: gpu.nvidia.small.multi # NVIDIA Tesla T4 2 GPU 4 vCPUs 15 GB RAM

  gpu_cuda11:
    environment:
      CUDA_VERSION: "11.7"
      CUDA_HOME: "/usr/local/cuda"
      PYTHONUNBUFFERED: 1
    machine:
      image: ubuntu-2004:202107-02
    resource_class: gpu.nvidia.small.multi # NVIDIA Tesla T4 2 GPU 4 vCPUs 15 GB RAM

# -------------------------------------------------------------------------------------
# Re-usable commands
# -------------------------------------------------------------------------------------
setup_cuda10_libs: &setup_cuda10_libs
  - run:
      name: Setup CUDA drivers and libraries
      working_directory: ~/
      command: |
        # ubuntu's default gcc9.3 is too recent for cuda10.2
        sudo apt-get install -y gcc-8 g++-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 20
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 20
        # download and install nvidia drivers, cuda, etc
        wget --quiet --no-clobber -P ~/nvidia-downloads https://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_440.33.01_linux.run
        time sudo /bin/bash nvidia-downloads/cuda_10.2.89_440.33.01_linux.run --no-drm --silent --driver --toolkit
        sudo ldconfig /usr/local/cuda/lib64
        echo "Done installing NVIDIA drivers and CUDA libraries (10.2)"
        nvidia-smi

setup_cuda11_3_libs: &setup_cuda11_3_libs
  - run:
      name: Setup CUDA drivers and libraries
      working_directory: ~/
      command: |
        # download and install nvidia drivers, cuda, etc
        wget --quiet --no-clobber -P ~/nvidia-downloads https://developer.download.nvidia.com/compute/cuda/11.3.0/local_installers/cuda_11.3.0_465.19.01_linux.run
        time sudo /bin/bash nvidia-downloads/cuda_11.3.0_465.19.01_linux.run --no-drm --silent --driver --toolkit
        sudo ldconfig /usr/local/cuda/lib64
        echo "Done installing NVIDIA drivers and CUDA libraries (11.3)"
        nvidia-smi

setup_cuda11_libs: &setup_cuda11_libs
  - run:
      name: Setup CUDA drivers and libraries
      working_directory: ~/
      command: |
        # download and install nvidia drivers, cuda, etc
        wget --quiet --no-clobber -P ~/nvidia-downloads https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run
        time sudo /bin/bash nvidia-downloads/cuda_11.7.0_515.43.04_linux.run --no-drm --silent --driver --toolkit
        sudo ldconfig /usr/local/cuda/lib64
        echo "Done installing NVIDIA drivers and CUDA libraries (11.7)"
        nvidia-smi

setup_project: &setup_project
  - run:
      name: Setting up project
      working_directory: ~/project
      command: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc
        cmake --build build -- -j16

run_tests: &run_tests
  - run:
      name: Running tests
      working_directory: ~/project
      command: |
        ctest --test-dir build

# -------------------------------------------------------------------------------------
# Jobs
# -------------------------------------------------------------------------------------
jobs:
  unittests_gpu17_cuda10:
    executor: gpu_cuda10
    steps:
      - checkout
      - <<: *setup_cuda10_libs
      - <<: *setup_project
      - <<: *run_tests

  unittests_gpu17_cuda11:
    executor: gpu_cuda11
    steps:
      - checkout
      - <<: *setup_cuda11_libs
      - <<: *setup_project
      - <<: *run_tests

workflows:
  version: 2
  build:
    jobs:
      - unittests_gpu17_cuda10
      - unittests_gpu17_cuda11
